"""Squashed initial schema for V3 production

Revision ID: 618783807a2f
Revises: 
Create Date: 2026-09-20 13:06:20.778925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618783807a2f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('minimum_app_version', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_name', 'version', name='uq_dataset_version')
    )
    op.create_index(op.f('ix_data_versions_dataset_name'), 'data_versions', ['dataset_name'], unique=False)
    op.create_index(op.f('ix_data_versions_id'), 'data_versions', ['id'], unique=False)
    op.create_index('uq_active_data_version', 'data_versions', ['dataset_name'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('emergency_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_event_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='eventstatus'), nullable=True),
    sa.Column('is_simulation', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_events_external_event_id'), 'emergency_events', ['external_event_id'], unique=True)
    op.create_index(op.f('ix_emergency_events_id'), 'emergency_events', ['id'], unique=False)
    op.create_index('uq_single_active_tsunami_event', 'emergency_events', ['status', 'is_simulation'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_table('evacuation_points',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('floors', sa.Integer(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('type', sa.Enum('TES', 'TEA', name='evacuationpointtype'), nullable=True),
    sa.Column('structural_condition', sa.Enum('UNKNOWN', 'LAYAK', 'RUSAK_RINGAN', 'RUSAK_SEDANG', 'RUSAK_BERAT', name='structuralcondition'), nullable=True),
    sa.Column('operational_status', sa.Enum('UNKNOWN', 'OPEN', 'CLOSED', 'LIMITED', name='operationalstatus'), nullable=True),
    sa.Column('status_source', sa.String(), nullable=True),
    sa.Column('status_reason', sa.String(), nullable=True),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('entrance_coord', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_evacuation_points_entrance_coord', 'evacuation_points', ['entrance_coord'], unique=False, postgresql_using='gist')
    op.create_index('idx_evacuation_points_location', 'evacuation_points', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_evacuation_points_external_id'), 'evacuation_points', ['external_id'], unique=True)
    op.create_index(op.f('ix_evacuation_points_id'), 'evacuation_points', ['id'], unique=False)
    op.create_index(op.f('ix_evacuation_points_name'), 'evacuation_points', ['name'], unique=False)
    op.create_table('inundation_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('danger_level', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_inundation_zones_geometry', 'inundation_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_inundation_zones_id'), 'inundation_zones', ['id'], unique=False)
    op.create_table('safe_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_safe_zones_geometry', 'safe_zones', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_safe_zones_id'), 'safe_zones', ['id'], unique=False)
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('evacuation_point_id', sa.BigInteger(), nullable=False),
    sa.Column('device_hash', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['evacuation_point_id'], ['evacuation_points.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'device_hash', name='uq_event_device')
    )
    op.create_index(op.f('ix_checkins_device_hash'), 'checkins', ['device_hash'], unique=False)
    op.create_index(op.f('ix_checkins_event_id'), 'checkins', ['event_id'], unique=False)
    op.create_index(op.f('ix_checkins_id'), 'checkins', ['id'], unique=False)
    op.create_table('event_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='eventstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('operator_name', sa.String(), nullable=False),
    sa.Column('change_reason', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_status_history_event_id'), 'event_status_history', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_status_history_id'), 'event_status_history', ['id'], unique=False)
    op.create_table('obstructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('edge_external_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'EXPIRED', name='obstructionstatus'), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['data_versions.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'dataset_version_id', 'edge_external_id', name='uq_event_dataset_edge')
    )
    op.create_index(op.f('ix_obstructions_dataset_version_id'), 'obstructions', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_obstructions_edge_external_id'), 'obstructions', ['edge_external_id'], unique=False)
    op.create_index(op.f('ix_obstructions_event_id'), 'obstructions', ['event_id'], unique=False)
    op.create_index(op.f('ix_obstructions_id'), 'obstructions', ['id'], unique=False)
    op.create_table('route_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('edge_external_id', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['data_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'edge_external_id', name='uq_dataset_edge')
    )
    op.create_index('idx_route_edges_geometry', 'route_edges', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_route_edges_dataset_version_id'), 'route_edges', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_route_edges_edge_external_id'), 'route_edges', ['edge_external_id'], unique=False)
    op.create_index(op.f('ix_route_edges_id'), 'route_edges', ['id'], unique=False)
    op.create_table('shelter_occupancy_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('evacuation_point_id', sa.BigInteger(), nullable=False),
    sa.Column('device_hash', sa.String(), nullable=False),
    sa.Column('level', sa.Enum('LOW', 'MODERATE', 'FULL', name='occupancylevel'), nullable=False),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evacuation_point_id'], ['evacuation_points.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['emergency_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'evacuation_point_id', 'device_hash', name='uq_occupancy_event_point_device')
    )
    op.create_index(op.f('ix_shelter_occupancy_reports_device_hash'), 'shelter_occupancy_reports', ['device_hash'], unique=False)
    op.create_index(op.f('ix_shelter_occupancy_reports_evacuation_point_id'), 'shelter_occupancy_reports', ['evacuation_point_id'], unique=False)
    op.create_index(op.f('ix_shelter_occupancy_reports_event_id'), 'shelter_occupancy_reports', ['event_id'], unique=False)
    op.create_index(op.f('ix_shelter_occupancy_reports_id'), 'shelter_occupancy_reports', ['id'], unique=False)
    op.create_table('obstruction_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obstruction_id', sa.Integer(), nullable=False),
    sa.Column('device_hash', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['obstruction_id'], ['obstructions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('obstruction_id', 'device_hash', name='uq_obstruction_device')
    )
    op.create_index('idx_obstruction_reports_location', 'obstruction_reports', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_obstruction_reports_device_hash'), 'obstruction_reports', ['device_hash'], unique=False)
    op.create_index(op.f('ix_obstruction_reports_id'), 'obstruction_reports', ['id'], unique=False)
    op.create_index(op.f('ix_obstruction_reports_obstruction_id'), 'obstruction_reports', ['obstruction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obstruction_reports_obstruction_id'), table_name='obstruction_reports')
    op.drop_index(op.f('ix_obstruction_reports_id'), table_name='obstruction_reports')
    op.drop_index(op.f('ix_obstruction_reports_device_hash'), table_name='obstruction_reports')
    op.drop_index('idx_obstruction_reports_location', table_name='obstruction_reports', postgresql_using='gist')
    op.drop_table('obstruction_reports')
    op.drop_index(op.f('ix_shelter_occupancy_reports_id'), table_name='shelter_occupancy_reports')
    op.drop_index(op.f('ix_shelter_occupancy_reports_event_id'), table_name='shelter_occupancy_reports')
    op.drop_index(op.f('ix_shelter_occupancy_reports_evacuation_point_id'), table_name='shelter_occupancy_reports')
    op.drop_index(op.f('ix_shelter_occupancy_reports_device_hash'), table_name='shelter_occupancy_reports')
    op.drop_table('shelter_occupancy_reports')
    op.drop_index(op.f('ix_route_edges_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_edge_external_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_dataset_version_id'), table_name='route_edges')
    op.drop_index('idx_route_edges_geometry', table_name='route_edges', postgresql_using='gist')
    op.drop_table('route_edges')
    op.drop_index(op.f('ix_obstructions_id'), table_name='obstructions')
    op.drop_index(op.f('ix_obstructions_event_id'), table_name='obstructions')
    op.drop_index(op.f('ix_obstructions_edge_external_id'), table_name='obstructions')
    op.drop_index(op.f('ix_obstructions_dataset_version_id'), table_name='obstructions')
    op.drop_table('obstructions')
    op.drop_index(op.f('ix_event_status_history_id'), table_name='event_status_history')
    op.drop_index(op.f('ix_event_status_history_event_id'), table_name='event_status_history')
    op.drop_table('event_status_history')
    op.drop_index(op.f('ix_checkins_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_event_id'), table_name='checkins')
    op.drop_index(op.f('ix_checkins_device_hash'), table_name='checkins')
    op.drop_table('checkins')
    op.drop_index(op.f('ix_safe_zones_id'), table_name='safe_zones')
    op.drop_index('idx_safe_zones_geometry', table_name='safe_zones', postgresql_using='gist')
    op.drop_table('safe_zones')
    op.drop_index(op.f('ix_inundation_zones_id'), table_name='inundation_zones')
    op.drop_index('idx_inundation_zones_geometry', table_name='inundation_zones', postgresql_using='gist')
    op.drop_table('inundation_zones')
    op.drop_index(op.f('ix_evacuation_points_name'), table_name='evacuation_points')
    op.drop_index(op.f('ix_evacuation_points_id'), table_name='evacuation_points')
    op.drop_index(op.f('ix_evacuation_points_external_id'), table_name='evacuation_points')
    op.drop_index('idx_evacuation_points_location', table_name='evacuation_points', postgresql_using='gist')
    op.drop_index('idx_evacuation_points_entrance_coord', table_name='evacuation_points', postgresql_using='gist')
    op.drop_table('evacuation_points')
    op.drop_index('uq_single_active_tsunami_event', table_name='emergency_events', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_emergency_events_id'), table_name='emergency_events')
    op.drop_index(op.f('ix_emergency_events_external_event_id'), table_name='emergency_events')
    op.drop_table('emergency_events')
    op.drop_index('uq_active_data_version', table_name='data_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_data_versions_id'), table_name='data_versions')
    op.drop_index(op.f('ix_data_versions_dataset_name'), table_name='data_versions')
    op.drop_table('data_versions')
    # ### end Alembic commands ###
