"""v3_final_revisions

Revision ID: d3354ac33c10
Revises: fd8970c8bf8f
Create Date: 2026-08-10 19:57:48.281959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd3354ac33c10'
down_revision: Union[str, Sequence[str], None] = 'fd8970c8bf8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Handle StructuralCondition enum creation
    structural_condition_enum = sa.Enum('UNKNOWN', 'LAYAK', 'RUSAK_RINGAN', 'RUSAK_SEDANG', 'RUSAK_BERAT', name='structuralcondition')
    structural_condition_enum.create(op.get_bind(), checkfirst=True)
    
    # Handle OperationalStatus enum replacement
    op.execute("ALTER TYPE operationalstatus RENAME TO operationalstatus_old")
    operational_status_enum = sa.Enum('UNKNOWN', 'OPEN', 'CLOSED', 'LIMITED', name='operationalstatus')
    operational_status_enum.create(op.get_bind(), checkfirst=True)
    # Map old values to new ones as text so cast succeeds
    op.execute("UPDATE evacuation_points SET operational_status = 'OPEN'::operationalstatus_old WHERE operational_status = 'LAYAK'::operationalstatus_old OR operational_status = 'RUSAK_RINGAN'::operationalstatus_old")
    op.execute("UPDATE evacuation_points SET operational_status = 'CLOSED'::operationalstatus_old WHERE operational_status = 'RUSAK_BERAT'::operationalstatus_old OR operational_status = 'TIDAK_LAYAK'::operationalstatus_old")
    op.execute("ALTER TABLE evacuation_points ALTER COLUMN operational_status TYPE operationalstatus USING operational_status::text::operationalstatus")
    op.execute("DROP TYPE operationalstatus_old")
    
    # Handle EventStatus enum replacement
    op.execute("ALTER TYPE eventstatus RENAME TO eventstatus_old")
    event_status_enum = sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED', name='eventstatus')
    event_status_enum.create(op.get_bind(), checkfirst=True)
    # Map old values
    op.execute("UPDATE emergency_events SET status = 'CLOSED'::eventstatus_old WHERE status = 'RESOLVED'::eventstatus_old")
    op.execute("UPDATE emergency_events SET status = 'CANCELLED'::eventstatus_old WHERE status = 'FALSE_ALARM'::eventstatus_old")
    op.execute("ALTER TABLE emergency_events ALTER COLUMN status TYPE eventstatus USING status::text::eventstatus")
    op.execute("DROP TYPE eventstatus_old")
    
    # Handle ObstructionStatus enum replacement
    op.execute("ALTER TYPE obstructionstatus RENAME TO obstructionstatus_old")
    obstruction_status_enum = sa.Enum('PENDING', 'CONFIRMED', 'REJECTED', 'EXPIRED', name='obstructionstatus')
    obstruction_status_enum.create(op.get_bind(), checkfirst=True)
    # Map old values
    op.execute("UPDATE obstructions SET status = 'CONFIRMED'::obstructionstatus_old WHERE status = 'CROWD_CONFIRMED'::obstructionstatus_old OR status = 'OFFICIAL_CONFIRMED'::obstructionstatus_old")
    op.execute("ALTER TABLE obstructions ALTER COLUMN status TYPE obstructionstatus USING status::text::obstructionstatus")
    op.execute("DROP TYPE obstructionstatus_old")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_version_id', sa.Integer(), nullable=False),
    sa.Column('edge_external_id', sa.String(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['data_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_version_id', 'edge_external_id', name='uq_dataset_edge')
    )
    op.create_index(op.f('ix_route_edges_dataset_version_id'), 'route_edges', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_route_edges_edge_external_id'), 'route_edges', ['edge_external_id'], unique=False)
    op.create_index(op.f('ix_route_edges_id'), 'route_edges', ['id'], unique=False)
    op.create_index('uq_active_data_version', 'data_versions', ['dataset_name'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('uq_single_active_tsunami_event', 'emergency_events', ['status'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.add_column('evacuation_points', sa.Column('structural_condition', structural_condition_enum, nullable=True))
    op.add_column('evacuation_points', sa.Column('status_source', sa.String(), nullable=True))
    op.add_column('evacuation_points', sa.Column('status_reason', sa.String(), nullable=True))
    op.add_column('evacuation_points', sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_obstruction_device', 'obstruction_reports', ['obstruction_id', 'device_hash'])
    
    # Provide default dataset_version_id and edge_external_id to prevent NOT NULL errors on existing obstructions
    op.add_column('obstructions', sa.Column('dataset_version_id', sa.Integer(), nullable=True))
    op.add_column('obstructions', sa.Column('edge_external_id', sa.String(), nullable=True))
    
    # Assign dummy data to existing obstructions
    op.execute("UPDATE obstructions SET dataset_version_id = 1, edge_external_id = edge_id::text WHERE dataset_version_id IS NULL")
    
    op.alter_column('obstructions', 'dataset_version_id', nullable=False)
    op.alter_column('obstructions', 'edge_external_id', nullable=False)
    
    op.alter_column('obstructions', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_obstructions_edge_id'), table_name='obstructions')
    op.create_index(op.f('ix_obstructions_dataset_version_id'), 'obstructions', ['dataset_version_id'], unique=False)
    op.create_index(op.f('ix_obstructions_edge_external_id'), 'obstructions', ['edge_external_id'], unique=False)
    op.create_unique_constraint('uq_event_dataset_edge', 'obstructions', ['event_id', 'dataset_version_id', 'edge_external_id'])
    op.create_foreign_key('fk_obstructions_dataset_version', 'obstructions', 'data_versions', ['dataset_version_id'], ['id'])
    op.drop_column('obstructions', 'dataset_version')
    op.drop_column('obstructions', 'edge_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("TRUNCATE TABLE obstructions CASCADE")
    op.add_column('obstructions', sa.Column('edge_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('obstructions', sa.Column('dataset_version', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_event_dataset_edge', 'obstructions', type_='unique')
    op.drop_index(op.f('ix_obstructions_edge_external_id'), table_name='obstructions')
    op.drop_index(op.f('ix_obstructions_dataset_version_id'), table_name='obstructions')
    op.create_index(op.f('ix_obstructions_edge_id'), 'obstructions', ['edge_id'], unique=False)
    op.alter_column('obstructions', 'event_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('obstructions', 'edge_external_id')
    op.drop_column('obstructions', 'dataset_version_id')
    op.drop_constraint('uq_obstruction_device', 'obstruction_reports', type_='unique')
    op.drop_column('evacuation_points', 'status_updated_at')
    op.drop_column('evacuation_points', 'status_reason')
    op.drop_column('evacuation_points', 'status_source')
    op.drop_column('evacuation_points', 'structural_condition')
    op.drop_index('uq_single_active_tsunami_event', table_name='emergency_events', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index('uq_active_data_version', table_name='data_versions', postgresql_where=sa.text('is_active = true'))
    op.drop_index(op.f('ix_route_edges_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_edge_external_id'), table_name='route_edges')
    op.drop_index(op.f('ix_route_edges_dataset_version_id'), table_name='route_edges')
    op.drop_table('route_edges')
    # ### end Alembic commands ###
    
    # Revert OperationalStatus
    op.execute("ALTER TYPE operationalstatus RENAME TO operationalstatus_old")
    operational_status_enum = sa.Enum('LAYAK', 'RUSAK_RINGAN', 'RUSAK_BERAT', 'TIDAK_LAYAK', name='operationalstatus')
    operational_status_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE evacuation_points ALTER COLUMN operational_status TYPE operationalstatus USING operational_status::text::operationalstatus")
    op.execute("DROP TYPE operationalstatus_old")
    
    # Revert EventStatus
    op.execute("ALTER TYPE eventstatus RENAME TO eventstatus_old")
    event_status_enum = sa.Enum('ACTIVE', 'RESOLVED', 'FALSE_ALARM', name='eventstatus')
    event_status_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE emergency_events ALTER COLUMN status TYPE eventstatus USING status::text::eventstatus")
    op.execute("DROP TYPE eventstatus_old")
    
    # Revert ObstructionStatus
    op.execute("ALTER TYPE obstructionstatus RENAME TO obstructionstatus_old")
    obstruction_status_enum = sa.Enum('PENDING', 'CROWD_CONFIRMED', 'OFFICIAL_CONFIRMED', 'REJECTED', 'EXPIRED', name='obstructionstatus')
    obstruction_status_enum.create(op.get_bind(), checkfirst=True)
    op.execute("ALTER TABLE obstructions ALTER COLUMN status TYPE obstructionstatus USING status::text::obstructionstatus")
    op.execute("DROP TYPE obstructionstatus_old")
    
    op.execute("DROP TYPE structuralcondition")
